services:
  redis:
    image: redis:6.2.11-alpine
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    sysctls:
      net.core.somaxconn: 1024
volumes:
  cache:
    driver: local
